local dashboard = require("dashboard")

local header = {
	[[                                     ]],
	[[                                     ]],
	[[                                     ]],
	[[                                     ]],
	[[      __                _            ]],
	[[   /\ \ \___  ___/\   /(_)_ __ ___   ]],
	[[  /  \/ / _ \/ _ \ \ / | | '_ ` _ \  ]],
	[[ / /\  |  __| (_) \ V /| | | | | | | ]],
	[[ \_\ \/ \___|\___/ \_/ |_|_| |_| |_| ]],
	[[                                     ]],
	[[                                     ]],
	[[                                     ]],
	[[                                     ]],
	[[                                     ]],
}

dashboard.setup({
	theme = "doom",
	config = {
		header = header,
		center = {
			{
				icon = "",
				icon_hl = "Character",
				desc = "   New file        ",
				desc_hl = "Function",
				key = "n",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "ene",
			},
			{
				icon = "󰈢",
				icon_hl = "Character",
				desc = "   Open file       ",
				desc_hl = "Function",
				key = "f",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "Telescope find_files",
			},
			{
				icon = "󱋡",
				icon_hl = "Character",
				desc = "   Recent files    ",
				desc_hl = "Function",
				key = "r",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "Telescope oldfiles",
			},
			{
				icon = "󰍉",
				icon_hl = "Character",
				desc = "   Find text       ",
				desc_hl = "Function",
				key = "t",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "Telescope live_grep",
			},
			{
				icon = "󰒲",
				icon_hl = "Character",
				desc = "   Lazy            ",
				desc_hl = "Function",
				key = "l",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "Lazy",
			},
			{
				icon = "󰏖",
				icon_hl = "Character",
				desc = "   Mason           ",
				desc_hl = "Function",
				key = "m",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "Mason",
			},
			{
				icon = "󰗼",
				icon_hl = "Character",
				desc = "   Quit            ",
				desc_hl = "Function",
				key = "q",
				key_hl = "Number",
				keymap = "",
				key_format = " %s",
				action = "qa",
			},
		},
		footer = {},
	},
})
